name: Test and Lint democracy_now_scraper

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: write-all

jobs:
  quality_check:
    name: pytest and pylint
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v4

    # Install Python
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install required packages
    - name: Install packages
      run: |
        pip install pylint pytest pytest--cov
        pip install -r ./democracy_now_scraper/requirements.txt
    
    # Run pytest and check coverage
    - name: Run pytest and check test coverage
      run: |
        pytest ./democracy_now_scraper/ --cov
      continue-on-error: false
    
    # Run pylint
    - name: Run pylint
      run: |
        find ./democracy_now_scraper/ -name "*.py" | xargs pylint --fail-under=8